### ISSUE TITLE
connection failure attempting to load Operators from git

### ISSUE THREAD

**Issue by senf666** [framefield/tooll#26]
I have a ssh key on github and successfully cloned git@github.com:framefield/tooll.git using ssh auth.

I then built and ran tool.exe but it complains:

![2016-08-18_1616](https://cloud.githubusercontent.com/assets/3512672/17780221/86893ff6-6562-11e6-8159-b2bad4b207e0.png)

`16:36:24.492 (INF): Tooll is starting up at 08/18/2016 16:36:24
16:36:24.497 (INF): Version: T2 - 0.0.2.6.666 (master, 17e1aac)
16:36:26.693 (INF): NSch.JSchException: Auth fail
   at NSch.Session.Connect(Int32 connectTimeout)
   at NGit.Transport.JschConfigSessionFactory.GetSession(URIish uri, CredentialsProvider credentialsProvider, FS fs, Int32 tms)
16:36:26.697 (INF): NGit.Errors.TransportException: git@github.com:framefield/tooll_private_operators.git: Auth fail
   at NGit.Transport.JschConfigSessionFactory.GetSession(URIish uri, CredentialsProvider credentialsProvider, FS fs, Int32 tms)
   at NGit.Transport.SshTransport.GetSession()
   at NGit.Transport.TransportGitSsh.SshFetchConnection..ctor(TransportGitSsh _enclosing)
   at NGit.Transport.TransportGitSsh.OpenFetch()
   at NGit.Transport.FetchProcess.ExecuteImp(ProgressMonitor monitor, FetchResult result)
   at NGit.Transport.FetchProcess.Execute(ProgressMonitor monitor, FetchResult result)
   at NGit.Transport.Transport.Fetch(ProgressMonitor monitor, ICollection`1 toFetch)
   at NGit.Api.FetchCommand.Call()
`
Why is it complaining about the auth when cloning the repo above went fine ? This appears similar to https://github.com/framefield/tooll/issues/2

thanks in advance.

**Comment by pixtur** [comment]
Thanks for posting. This is indeed an issue trigged by a misconfiguraiton within `ProjectSettings.json` file. It links to a non-public repository. 

Can you try to fix it by adjusting the respective line to...

```
  "Git.OperatorRepositoryURL": "git@github.com:framefield/tooll_operators.git",
```

**Comment by pixtur** [comment]
Please reopen, if it didn't work.

**Comment by DannyCork** [comment]
test
